stages:
  - test
  - sonarqube
  - deploy

test-coverage:
  stage: test
  image: python:3.10-alpine
  before_script:
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
  script:
    - coverage run manage.py test
    - coverage report -m
    - coverage xml -i
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/coverage.xml

test-coverage:
  stage: test
  image: python:3.10-alpine
  before_script:
    - pip install -r requirements.txt
    - python manage.py makemigrations
    - python manage.py migrate
  script:
    - coverage run manage.py test
    - coverage report -m
    - coverage xml -i
  artifacts:
    expire_in: 1 hour
    paths:
      - $CI_PROJECT_DIR/coverage.xml
  allow_failure: true

sonarqube-check:
  stage: sonarqube
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
  allow_failure: true

deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - staging
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway link --environment production 62dc03ef-d0cf-4ee7-9436-11dc17e27968
    - RAILWAY_TOKEN=$RAILWAY_TOKEN railway up --service=$RAILWAY_SERVICE_NAME -d

