# Generated by Django 4.1 on 2023-05-08 12:40

from django.db import migrations, models
import django.db.models.deletion
import periode.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(max_length=9, validators=[periode.models.validate_tahun_ajaran])),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], default='Ganjil', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeSekarang',
            fields=[
                ('periode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='periode.periode')),
            ],
        ),
    ]
