# Generated by Django 4.1.7 on 2023-05-25 13:52

from django.db import migrations, models
import django.db.models.deletion
import periode.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_ajaran', models.CharField(max_length=9, validators=[periode.models.tahun_ajaran_validator])),
                ('semester', models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Pendek', 'Pendek')], default='Ganjil', max_length=6)),
                ('bulan_mulai', models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MEI', 'MEI'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGT', 'AGT'), ('SEP', 'SEP'), ('OKT', 'OKT'), ('NOV', 'NOV'), ('DES', 'DES')], default='JAN', max_length=3)),
                ('bulan_selesai', models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MEI', 'MEI'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGT', 'AGT'), ('SEP', 'SEP'), ('OKT', 'OKT'), ('NOV', 'NOV'), ('DES', 'DES')], default='MEI', max_length=3)),
                ('daftar_ta', models.ManyToManyField(to='accounts.teachingassistantprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeSekarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='periode.periode')),
            ],
        ),
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.UniqueConstraint(fields=('tahun_ajaran', 'semester'), name='unique_migration_host_combination'),
        ),
    ]
