# Generated by Django 4.1.7 on 2023-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('periode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='daftar_ta',
            field=models.ManyToManyField(to='authentication.role'),
        ),
    ]
