# Generated by Django 4.1.7 on 2023-12-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_univ_univ'),
        ('periode', '0002_periodesekarang_univ'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='periode',
            name='unique_migration_host_combination',
        ),
        migrations.AddField(
            model_name='periode',
            name='univ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.univchoices'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.UniqueConstraint(fields=('tahun_ajaran', 'semester', 'univ'), name='unique_migration_host_combination'),
        ),
    ]
