# Generated by Django 4.1 on 2023-05-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periode', '0002_periodesekarang_id_alter_periodesekarang_periode'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='periode',
            constraint=models.UniqueConstraint(fields=('tahun_ajaran', 'semester'), name='unique_migration_host_combination'),
        ),
    ]
