# Generated by Django 4.1.7 on 2023-05-17 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('periode', '0002_alter_periode_daftar_ta'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.role')),
            ],
        ),
        migrations.AlterField(
            model_name='periode',
            name='daftar_ta',
            field=models.ManyToManyField(to='periode.statusta'),
        ),
    ]
