# Generated by Django 4.1.7 on 2023-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periode', '0003_periode_unique_migration_host_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='semester',
            field=models.CharField(choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap'), ('Pendek', 'Pendek')], default='Ganjil', max_length=6),
        ),
    ]
