# Generated by Django 4.1.7 on 2023-05-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teachingassistantprofile_prodi'),
        ('periode', '0003_statusta_alter_periode_daftar_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.teachingassistantprofile'),
        ),
    ]
