# Generated by Django 4.1.7 on 2023-05-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periode', '0005_alter_periode_daftar_ta_delete_statusta'),
    ]

    operations = [
        migrations.AddField(
            model_name='periode',
            name='bulan_mulai',
            field=models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MEI', 'MEI'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGT', 'AGT'), ('SEP', 'SEP'), ('OKT', 'OKT'), ('NOV', 'NOV'), ('DES', 'DES')], default='JAN', max_length=3),
        ),
        migrations.AddField(
            model_name='periode',
            name='bulan_selesai',
            field=models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MEI', 'MEI'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGT', 'AGT'), ('SEP', 'SEP'), ('OKT', 'OKT'), ('NOV', 'NOV'), ('DES', 'DES')], default='MEI', max_length=3),
        ),
    ]
