# Generated by Django 4.1.7 on 2023-05-12 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('periode', '0004_alter_periode_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Persiapan Kuliah', 'Persiapan Kuliah'), ('Penyelenggaraan Kuliah', 'Penyelenggaraan Kuliah'), ('Dukungan Kuliah Kakak Asuh', 'Dukungan Kuliah Kakak Asuh'), ('Pengembangan Institusi', 'Pengembangan Institusi'), ('Riset dan Pusilkom', 'Riset dan Pusilkom')], max_length=30)),
                ('jenis_pekerjaan', models.CharField(max_length=20)),
                ('detail_kegiatan', models.CharField(max_length=100)),
                ('pemberi_tugas', models.CharField(max_length=20)),
                ('uraian', models.CharField(max_length=200)),
                ('periode', models.CharField(choices=[('Semester Kuliah', 'Semester Kuliah'), ('Sepanjang Kontrak', 'Sepanjang Kontrak'), ('Bulanan', 'Bulanan'), ('Harian', 'Harian'), ('Adhoc', 'Adhoc')], max_length=20)),
                ('bulan_pengerjaan', models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MEI', 'MEI'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGT', 'AGT'), ('SEP', 'SEP'), ('OKT', 'OKT'), ('NOV', 'NOV'), ('DES', 'DES')], max_length=20)),
                ('jumlah_rencana_kinerja', models.IntegerField()),
                ('satuan_rencana_kinerja', models.CharField(max_length=20)),
                ('konversi_jam_rencana_kinerja', models.FloatField()),
                ('jumlah_realisasi_kinerja', models.IntegerField(blank=True, default=0, null=True)),
                ('satuan_realisasi_kinerja', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('konversi_jam_realisasi_kinerja', models.FloatField(blank=True, default=0, null=True)),
                ('periode_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periode.periode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLogTA',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Persiapan Kuliah', 'Persiapan Kuliah'), ('Penyelenggaraan Kuliah', 'Penyelenggaraan Kuliah'), ('Dukungan Kuliah Kakak Asuh', 'Dukungan Kuliah Kakak Asuh'), ('Pengembangan Institusi', 'Pengembangan Institusi'), ('Riset dan Pusilkom', 'Riset dan Pusilkom')], max_length=30)),
                ('jenis_pekerjaan', models.CharField(max_length=20)),
                ('detail_kegiatan', models.CharField(max_length=100)),
                ('pemberi_tugas', models.CharField(max_length=20)),
                ('uraian', models.CharField(max_length=200)),
                ('periode', models.CharField(choices=[('Semester Kuliah', 'Semester Kuliah'), ('Sepanjang Kontrak', 'Sepanjang Kontrak'), ('Bulanan', 'Bulanan'), ('Harian', 'Harian'), ('Adhoc', 'Adhoc')], max_length=20)),
                ('bulan_pengerjaan', models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MEI', 'MEI'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGT', 'AGT'), ('SEP', 'SEP'), ('OKT', 'OKT'), ('NOV', 'NOV'), ('DES', 'DES')], max_length=20)),
                ('jumlah_rencana_kinerja', models.IntegerField()),
                ('satuan_rencana_kinerja', models.CharField(max_length=20)),
                ('konversi_jam_rencana_kinerja', models.FloatField()),
                ('jumlah_realisasi_kinerja', models.IntegerField(blank=True, default=0, null=True)),
                ('satuan_realisasi_kinerja', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('konversi_jam_realisasi_kinerja', models.FloatField(blank=True, default=0, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('periode_log', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='periode.periode')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical log ta',
                'verbose_name_plural': 'historical log tas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
