# Generated by Django 4.1.7 on 2023-03-17 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Persiapan Kuliah', 'Persiapan Kuliah'), ('Penyelenggaraan Kuliah', 'Penyelenggaraan Kuliah'), ('Dukungan Kuliah Kakak Asuh', 'Dukungan Kuliah Kakak Asuh'), ('Pengembangan Institusi', 'Pengembangan Institusi'), ('Riset dan Pusilkom', 'Riset dan Pusilkom')], max_length=30)),
                ('jenis_pekerjaan', models.CharField(max_length=20)),
                ('detail_kegiatan', models.CharField(max_length=100)),
                ('pemberi_tugas', models.CharField(max_length=20)),
                ('uraian', models.CharField(max_length=200)),
                ('periode', models.CharField(choices=[('Semester Kuliah', 'Semester Kuliah'), ('Sepanjang Kontrak', 'Sepanjang Kontrak'), ('Bulanan', 'Bulanan'), ('Harian', 'Harian'), ('Adhoc', 'Adhoc')], max_length=20)),
                ('bulan_pengerjaan', models.CharField(choices=[('JAN', 'JAN'), ('FEB', 'FEB'), ('MAR', 'MAR'), ('APR', 'APR'), ('MEI', 'MEI'), ('JUN', 'JUN'), ('JUL', 'JUL'), ('AGT', 'AGT'), ('SEP', 'SEP'), ('OKT', 'OKT'), ('NOV', 'NOV'), ('DES', 'DES')], max_length=20)),
                ('jumlah_rencana_kinerja', models.IntegerField()),
                ('satuan_rencana_kinerja', models.CharField(max_length=20)),
                ('konversi_jam_rencana_kinerja', models.IntegerField()),
                ('jumlah_realisasi_kinerja', models.IntegerField(blank=True, default=0)),
                ('satuan_realisasi_kinerja', models.CharField(blank=True, default='', max_length=20)),
                ('konversi_jam_realisasi_kinerja', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
