# Generated by Django 4.1.7 on 2023-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengisianLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logta',
            name='konversi_jam_rencana_kinerja',
            field=models.FloatField(),
        ),
    ]
