# Generated by Django 4.1.7 on 2023-03-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pengisianLog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logta",
            name="jumlah_realisasi_kinerja",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="logta",
            name="konversi_jam_realisasi_kinerja",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="logta",
            name="satuan_realisasi_kinerja",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
