# Generated by Django 4.1.7 on 2023-05-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_teachingassistantprofile_bulan_mulai_and_more"),
        ("pengisianLog", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicallogta",
            old_name="konversi_jam_realisasi_kinerja",
            new_name="bobot_jam_realisasi_kinerja",
        ),
        migrations.RenameField(
            model_name="historicallogta",
            old_name="konversi_jam_rencana_kinerja",
            new_name="bobot_jam_rencana_kinerja",
        ),
        migrations.RenameField(
            model_name="logta",
            old_name="konversi_jam_realisasi_kinerja",
            new_name="bobot_jam_realisasi_kinerja",
        ),
        migrations.RenameField(
            model_name="logta",
            old_name="konversi_jam_rencana_kinerja",
            new_name="bobot_jam_rencana_kinerja",
        ),
        migrations.AddField(
            model_name="historicallogta",
            name="jam_kerja_realisasi",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicallogta",
            name="jam_kerja_rencana",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicallogta",
            name="matkul",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accounts.matakuliah",
            ),
        ),
        migrations.AddField(
            model_name="logta",
            name="jam_kerja_realisasi",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="logta",
            name="jam_kerja_rencana",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logta",
            name="matkul",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to="accounts.matakuliah",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicallogta",
            name="bulan_pengerjaan",
            field=models.CharField(
                choices=[
                    ("JAN", "JAN"),
                    ("FEB", "FEB"),
                    ("MAR", "MAR"),
                    ("APR", "APR"),
                    ("MEI", "MEI"),
                    ("JUN", "JUN"),
                    ("JUL", "JUL"),
                    ("AGT", "AGT"),
                    ("SEP", "SEP"),
                    ("OKT", "OKT"),
                    ("NOV", "NOV"),
                    ("DES", "DES"),
                    ("Semester Kuliah", "Semester Kuliah"),
                    ("Sepanjang Kontrak", "Sepanjang Kontrak"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicallogta",
            name="periode",
            field=models.CharField(
                choices=[
                    ("Adhoc", "Adhoc"),
                    ("Semester Kuliah", "Semester Kuliah"),
                    ("Sepanjang Kontrak", "Sepanjang Kontrak"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="logta",
            name="bulan_pengerjaan",
            field=models.CharField(
                choices=[
                    ("JAN", "JAN"),
                    ("FEB", "FEB"),
                    ("MAR", "MAR"),
                    ("APR", "APR"),
                    ("MEI", "MEI"),
                    ("JUN", "JUN"),
                    ("JUL", "JUL"),
                    ("AGT", "AGT"),
                    ("SEP", "SEP"),
                    ("OKT", "OKT"),
                    ("NOV", "NOV"),
                    ("DES", "DES"),
                    ("Semester Kuliah", "Semester Kuliah"),
                    ("Sepanjang Kontrak", "Sepanjang Kontrak"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="logta",
            name="periode",
            field=models.CharField(
                choices=[
                    ("Adhoc", "Adhoc"),
                    ("Semester Kuliah", "Semester Kuliah"),
                    ("Sepanjang Kontrak", "Sepanjang Kontrak"),
                ],
                max_length=20,
            ),
        ),
    ]
