# Generated by Django 4.1.7 on 2023-03-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pengisianLog", "0002_alter_logta_konversi_jam_rencana_kinerja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logta",
            name="konversi_jam_realisasi_kinerja",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
