# Generated by Django 4.1.7 on 2023-03-14 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pengisianLog', '0002_logta_jumlah_realisasi_kinerja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logta',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
