# Generated by Django 4.1.7 on 2023-03-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pengisianLog", "0003_alter_logta_konversi_jam_realisasi_kinerja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logta",
            name="jumlah_realisasi_kinerja",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="logta",
            name="konversi_jam_realisasi_kinerja",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="logta",
            name="satuan_realisasi_kinerja",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
