# Generated by Django 4.1.7 on 2023-05-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengisianLog', '0005_historicallogta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallogta',
            name='kategori',
            field=models.CharField(choices=[('Dukungan Kuliah Kakak Asuh', 'Dukungan Kuliah Kakak Asuh'), ('Pengembangan Institusi', 'Pengembangan Institusi'), ('Penyelenggaraan Kuliah', 'Penyelenggaraan Kuliah'), ('Persiapan Kuliah', 'Persiapan Kuliah'), ('Riset dan Pusilkom', 'Riset dan Pusilkom')], max_length=30),
        ),
        migrations.AlterField(
            model_name='historicallogta',
            name='periode',
            field=models.CharField(choices=[('Adhoc', 'Adhoc'), ('Bulanan', 'Bulanan'), ('Harian', 'Harian'), ('Semester Kuliah', 'Semester Kuliah'), ('Sepanjang Kontrak', 'Sepanjang Kontrak')], max_length=20),
        ),
        migrations.AlterField(
            model_name='logta',
            name='kategori',
            field=models.CharField(choices=[('Dukungan Kuliah Kakak Asuh', 'Dukungan Kuliah Kakak Asuh'), ('Pengembangan Institusi', 'Pengembangan Institusi'), ('Penyelenggaraan Kuliah', 'Penyelenggaraan Kuliah'), ('Persiapan Kuliah', 'Persiapan Kuliah'), ('Riset dan Pusilkom', 'Riset dan Pusilkom')], max_length=30),
        ),
        migrations.AlterField(
            model_name='logta',
            name='periode',
            field=models.CharField(choices=[('Adhoc', 'Adhoc'), ('Bulanan', 'Bulanan'), ('Harian', 'Harian'), ('Semester Kuliah', 'Semester Kuliah'), ('Sepanjang Kontrak', 'Sepanjang Kontrak')], max_length=20),
        ),
    ]
