# Generated by Django 4.1.7 on 2023-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingassistantprofile",
            name="bulan_mulai",
            field=models.CharField(
                choices=[
                    ("JAN", "JAN"),
                    ("FEB", "FEB"),
                    ("MAR", "MAR"),
                    ("APR", "APR"),
                    ("MEI", "MEI"),
                    ("JUN", "JUN"),
                    ("JUL", "JUL"),
                    ("AGT", "AGT"),
                    ("SEP", "SEP"),
                    ("OKT", "OKT"),
                    ("NOV", "NOV"),
                    ("DES", "DES"),
                ],
                default=1,
                max_length=3,
                verbose_name="Bulan Mulai",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teachingassistantprofile",
            name="bulan_selesai",
            field=models.CharField(
                choices=[
                    ("JAN", "JAN"),
                    ("FEB", "FEB"),
                    ("MAR", "MAR"),
                    ("APR", "APR"),
                    ("MEI", "MEI"),
                    ("JUN", "JUN"),
                    ("JUL", "JUL"),
                    ("AGT", "AGT"),
                    ("SEP", "SEP"),
                    ("OKT", "OKT"),
                    ("NOV", "NOV"),
                    ("DES", "DES"),
                ],
                default=4,
                max_length=3,
                verbose_name="Bulan Selesai",
            ),
            preserve_default=False,
        ),
    ]
