# Generated by Django 4.1.7 on 2023-05-26 14:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teachingassistantprofile_bulan_mulai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassistantprofile',
            name='tahun_mulai',
            field=models.CharField(default='2023', max_length=4, validators=[accounts.models.year_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachingassistantprofile',
            name='tahun_selesai',
            field=models.CharField(default='2023', max_length=4, validators=[accounts.models.year_validator]),
            preserve_default=False,
        ),
    ]
