# Generated by Django 4.1.7 on 2023-06-11 06:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teachingassistantprofile_tahun_mulai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassistantprofile',
            name='tahun_mulai',
            field=models.CharField(max_length=4, validators=[accounts.models.year_validator], verbose_name='Tahun Mulai'),
        ),
        migrations.AlterField(
            model_name='teachingassistantprofile',
            name='tahun_selesai',
            field=models.CharField(max_length=4, validators=[accounts.models.year_validator], verbose_name='Tahun Selesai'),
        ),
    ]
