# Generated by Django 4.1.7 on 2023-12-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_univchoices_univ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univ',
            name='univ',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.univchoices'),
        ),
    ]
